// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSVP.Server.Models;

#nullable disable

namespace RSVP.Server.Migrations
{
    [DbContext(typeof(RsvpDbContext))]
    partial class RsvpDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RSVP.Server.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int?>("EventRegistrationId")
                        .HasColumnType("int")
                        .HasColumnName("event_registration_id");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("status");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__20D6A9681696933F");

                    b.HasIndex(new[] { "EventRegistrationId" }, "UQ__Attendan__204276F51E0C45A2")
                        .IsUnique()
                        .HasFilter("[event_registration_id] IS NOT NULL");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("club_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClubId"));

                    b.Property<string>("ClubContact")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("club_contact");

                    b.Property<DateTime?>("ClubCreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("club_createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ClubDepartment")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("club_department");

                    b.Property<string>("ClubEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("club_email");

                    b.Property<string>("ClubName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("club_name");

                    b.Property<DateTime?>("ClubUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("club_updatedAt")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ClubId")
                        .HasName("PK__Club__BCAD3DD90E16358F");

                    b.ToTable("Club", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<decimal?>("EventAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("event_amount");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventDescription")
                        .HasColumnType("text")
                        .HasColumnName("event_description");

                    b.Property<string>("EventEligibility")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_eligibility");

                    b.Property<TimeOnly?>("EventEndTime")
                        .HasColumnType("time")
                        .HasColumnName("event_end_time");

                    b.Property<string>("EventMode")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("event_mode");

                    b.Property<string>("EventName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_name");

                    b.Property<int?>("EventNoOfSeats")
                        .HasColumnType("int")
                        .HasColumnName("event_no_of_seats");

                    b.Property<string>("EventPaid")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)")
                        .HasColumnName("event_paid");

                    b.Property<byte[]>("EventQr")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("event_qr");

                    b.Property<TimeOnly?>("EventStartTime")
                        .HasColumnType("time")
                        .HasColumnName("event_start_time");

                    b.Property<string>("EventStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("event_status");

                    b.Property<string>("EventVenue")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("event_venue");

                    b.Property<int?>("OrgId")
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    b.HasKey("EventId")
                        .HasName("PK__Event__2370F727E629DD51");

                    b.HasIndex("OrgId");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.EventRegistration", b =>
                {
                    b.Property<int>("EventRegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_reg_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventRegId"));

                    b.Property<int?>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<byte[]>("PaymentScreenshot")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("payment_screenshot");

                    b.Property<string>("StudentId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("student_id");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("transaction_id");

                    b.HasKey("EventRegId")
                        .HasName("PK__Event_Re__117515140124FB22");

                    b.HasIndex("EventId");

                    b.HasIndex("StudentId");

                    b.ToTable("Event_Registration", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.Organisation", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("org_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrgId"));

                    b.Property<int?>("ClubId")
                        .HasColumnType("int")
                        .HasColumnName("club_id");

                    b.Property<string>("OrgContact")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("org_contact");

                    b.Property<string>("OrgDepartment")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("org_department");

                    b.Property<string>("OrgEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("org_email");

                    b.Property<string>("OrgName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("org_name");

                    b.Property<int?>("OrgNoOfEvents")
                        .HasColumnType("int")
                        .HasColumnName("org_no_of_events");

                    b.Property<string>("OrgPassword")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("org_password");

                    b.Property<string>("OrgRole")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("org_role");

                    b.HasKey("OrgId")
                        .HasName("PK__Organisa__F6AD801253264259");

                    b.HasIndex("ClubId");

                    b.ToTable("Organisation", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.Otp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Otps");
                });

            modelBuilder.Entity("RSVP.Server.Models.Student", b =>
                {
                    b.Property<string>("Prn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PRN");

                    b.Property<string>("Batch")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("Contact")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Div")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Prn")
                        .HasName("PK__Student__C5732E11041F5F09");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.UserCredential", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("emailId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.HasKey("UserId")
                        .HasName("PK__User_Cre__B9BE370F879D2DF5");

                    b.HasIndex(new[] { "EmailId" }, "UQ__User_Cre__87355E73B760BF25")
                        .IsUnique();

                    b.ToTable("User_Credential", (string)null);
                });

            modelBuilder.Entity("RSVP.Server.Models.Attendance", b =>
                {
                    b.HasOne("RSVP.Server.Models.EventRegistration", "EventRegistration")
                        .WithOne("Attendance")
                        .HasForeignKey("RSVP.Server.Models.Attendance", "EventRegistrationId")
                        .HasConstraintName("FK__Attendanc__event__0880433F");

                    b.Navigation("EventRegistration");
                });

            modelBuilder.Entity("RSVP.Server.Models.Event", b =>
                {
                    b.HasOne("RSVP.Server.Models.Organisation", "Org")
                        .WithMany("Events")
                        .HasForeignKey("OrgId")
                        .HasConstraintName("FK__Event__org_id__7EF6D905");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("RSVP.Server.Models.EventRegistration", b =>
                {
                    b.HasOne("RSVP.Server.Models.Event", "Event")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK__Event_Reg__event__02C769E9");

                    b.HasOne("RSVP.Server.Models.Student", "Student")
                        .WithMany("EventRegistrations")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Event_Reg__stude__03BB8E22");

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("RSVP.Server.Models.Organisation", b =>
                {
                    b.HasOne("RSVP.Server.Models.Club", "Club")
                        .WithMany("Organisations")
                        .HasForeignKey("ClubId")
                        .HasConstraintName("FK__Organisat__club___7B264821");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("RSVP.Server.Models.Club", b =>
                {
                    b.Navigation("Organisations");
                });

            modelBuilder.Entity("RSVP.Server.Models.Event", b =>
                {
                    b.Navigation("EventRegistrations");
                });

            modelBuilder.Entity("RSVP.Server.Models.EventRegistration", b =>
                {
                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("RSVP.Server.Models.Organisation", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("RSVP.Server.Models.Student", b =>
                {
                    b.Navigation("EventRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
